declare module 'mediasoup' {

    //JSDoc comments formatted for https://typedoc.org

    //NOTE1: Review if consumer and producer can use a "base type" like Endpoint to define common properties and methods. As this concept is not reflected in documentation, maybe is problematic

    //NOTE2: Review if repeat on("event") in subclasses can be avoided. Maybe creating a method on(string) in superclass and redeclaring it in subclases. Transport > WebRtcTransport.

    const mediasoup: MediaSoup;

    export default mediasoup;

    export interface MediaSoup {

        /**The media soup version */
        readonly version: string;

        /**An event emitter that allows the application (or third party libraries) monitor Worker instances created by the application. See the Observer Events section below. */
        readonly observer: MediaSoupObserver; //TODO: Extends EventEmitter definition.

        /**Creates a new worker with the given settings. */
        createWorker(options: WorkerSettings): Promise<Worker>;

        /**Returns a cloned copy of the mediasoup supported RTP capabilities, specifically the content of the mediasoup/lib/supportedRtpCapabilities.js file. */
        getSupportedRtpCapabilities(): RtpCapabilities;

        /**Parses the given scalabilityMode string according to the rules in webrtc-svc. */
        parseScalabilityMode(scalabilityMode?: string): ScalabilityMode;
    }

    export interface MediaSoupObserver {
        /**Emitted when a new worker is created. */
        on(eventType: "newworker", handler: (worker: Worker) => void): void;
    }

    export interface ScalabilityMode {
        /**Number of spatial layers (by default 1) */
        spatialLayers: number;
        /**Number of temporal layers (by default 1) */
        temporalLayers: number;
    }

    export interface WorkerSettings {
        /**Logging level for logs generated by the media worker subprocesses (check the Debugging documentation). Valid values are "debug", "warn", "error" and "none". Default "error" */
        logLevel?: "debug" | "warn" | "error" | "none";

        /**Log tags for debugging. Check the list of available tags in Debugging documentation. Default [] */
        logTags?: string[];

        /**Minimun RTC port for ICE, DTLS, RTP, etc. Default 10000 */
        rtcMinPort?: number;

        /**Maximum RTC port for ICE, DTLS, RTP, etc. Default 59999 */
        rtcMaxPort?: number;

        /**Path to the DTLS public certificate file in PEM format. If unset, a certificate is dynamically created.*/
        dtlsCertificateFile?: string;

        /**	Path to the DTLS certificate private key file in PEM format. If unset, a certificate is dynamically created.*/
        dtlsPrivateKeyFile?: string;
    }

    export type WorkerUpdateableSettings = Pick<WorkerSettings, 'logLevel' | 'logTags'>;

    /**A worker represents a mediasoup C++ subprocess that runs in a single CPU core and handles Router instances.*/
    export interface Worker {

        /**The PID of the worker process. */
        readonly pid: number;

        /**Whether the worker is closed. */
        readonly closed: boolean;

        /**Observer events */
        readonly observer: WorkerObserver;

        /**Closes the worker. Triggers a "workerclose" event in all its routers.*/
        close(): void;

        /**Updates the worker settings in runtime. Just a subset of the worker settings can be updated. */
        updateSettings(settings: WorkerUpdateableSettings): Promise<void>;

        /**Creates a new router.*/
        createRouter(options: RouterOptions): Promise<Router>

        /**Emitted when the worker process unexpectedly dies. This should never happens (if it happens, it's a bug).*/
        on(eventType: "died", handler: () => void): void;
    }

    export interface WorkerObserver {
        /**Emitted when the worker is closed for whatever reason.*/
        on(eventType: "close", handler: () => void): void;
        /**Emitted when a new router is created.*/
        on(eventType: "newrouter", handler: (router: Router) => void): void;
    }

    /**Feature codecs such as RTX MUST NOT be placed into the mediaCodecs list. If preferredPayloadType is given in a RtpCodecCapability (although it's unnecessary) it's extremely recommended to use a value in the 96-127 range. */
    export interface RouterOptions {
        /**Router media codecs*/
        mediaCodecs?: RtpCodecCapability[];
    }

    export interface RtpCodecCapability {
        //TODO
    }

    /**A router enables injection, selection and forwarding of media streams through Transport instances created on it. Developers may think of a mediasoup router as if it were a "multi-party conference room", although mediasoup is much more low level than that and doesn't constrain itself to specific high level use cases (for instance, a "multi-party conference room" could involve various mediasoup routers, even in different physicals hosts).*/
    export interface Router {

        /**Router identifier.*/
        readonly id: string;

        /**Whether the router is closed.*/
        readonly closed: boolean;

        /**An Object with the RTP capabilities of the router. These capabilities are tipically needed by mediasoup clients to compute their sending RTP parameters. Check the RTP Parameters and Capabilities section for more details.*/
        readonly rtpCapabilities: RtpCapabilities;

        /**Observer events */
        readonly observer: RouterObserver;

        /**Closes the router. Triggers a "routerclose" event in all its transports and also "routerclose" event in all its RTP observers.*/
        close(): void;

        /**Creates a new WebRTC transport.*/
        createWebRtcTransport(options: WebRtcTransportOptions): Promise<WebRtcTransport>

        /**Creates a new plain RTP transport.*/
        createPlainRtpTransport(options: PlainRtpTransportOptions): Promise<PlainRtpTransport>

        /**Creates a new pipe transport.*/
        createPipeTransport(options: PipeTransportOptions): Promise<PipeTransport>

        /**Pipes the given media or data producer into another router in the same host. It creates an underlying PipeTransport (if not previously created) that interconnects both routers.<br>
        This is specially useful to expand broadcasting capabilities (one to many) by interconnecting different routers that run in separate workers (so in different CPU cores).
        Only one of producerId and dataProducerId must be provided.
        SCTP agruments will only apply the first time the underlying transports are created.
        //TODO Document parameters
        */
        pipeToRouter(params: {
            producerId?: string,
            dataProducerId?: string,
            router: Router,
            listenIp?: string,
            enableSctp?: boolean,
            numSctpStreams?: TransportNumSctpStreams
        }):
            Promise<{
                pipeConsumer: Consumer;
                pipeProducer: Producer
            }>

        /**Creates a new audio level observer.*/
        createAudioLevelObserver(options: AudioLevelObserverOptions): Promise<AudioLevelObserver>;

        /**Whether the given RTP capabilities are valid to consume the given producer. 
        //TODO: Document parameters
        */
        canConsume(params: {
            producerId: string;
            rtpCapabilities: RtpCapabilities
        }): boolean;

        /**Emitted when the worker this router belongs to is closed for whatever reason. The router itself is also closed. A "routerclose" event is triggered in all its transports and a "routerclose" event is triggered in all its RTP observers.*/
        on(eventType: "workerclose", handler: () => void): void;
    }

    export interface RouterObserver {
        /**Emitted when the router is closed for whatever reason.*/
        on(eventType: "close", handler: () => void): void;

        /**Emitted when a new transport is created.*/
        on(eventType: "newtransport", handler: (transport: Transport) => void): void;
    }

    export interface TransportListenIp {
        /**	Listening IPv4 or IPv6.*/
        ip: string;
        /**Announced IPv4 or IPv6 (useful when running mediasoup behind NAT with private IP).*/
        announcedIp?: string;
    }

    /**Both remoteIp and remotePort are unset until the media address of the remote endpoint is known, which happens after calling transport.connect() in PlainRtpTransport and PipeTransport, or via dynamic detection as it happens in WebRtcTransport (in which the remote media address is detected by ICE means), or in PlainRtpTransport (when using comedia mode).*/
    export interface TransportTuple {
        /**Local IP address.*/
        localIP: string;
        /**Local port*/
        localPort: number;
        /**Remote IP address*/
        remoteIp?: string;
        /**Remote port.*/
        remotePort?: number;
        /**Protocol*/
        protocol: "udp" | "tcp"
    }

    export interface TransportSctpParameters {
        /**Must always equal 5000.*/
        port: number;
        /**Initially requested number of outgoing SCTP streams.*/
        OS: number
        /**Maximum number of incoming SCTP streams.*/
        MIS: number;
        /**Maximum allowed size for SCTP messages.*/
        maxMessageSize: number;
    }

    /**Both OS and MIS are part of the SCTP INIT+ACK handshake. OS refers to the initial number of outgoing SCTP streams that the server side transport creates (to be used by DataConsumers), while MIS refers to the maximum number of incoming SCTP streams that the server side transport can receive (to be used by DataProducers). So, if the server side transport will just be used to create data producers (but no data consumers), OS can be low (~1). However, if data consumers are desired on the server side transport, OS must have a proper value and such a proper value depends on whether the remote endpoint supports  SCTP_ADD_STREAMS extension or not.<br>
    libwebrtc (Chrome, Safari, etc) does not enable SCTP_ADD_STREAMS so, if data consumers are required,  OS should be 1024 (the maximum number of DataChannels that libwebrtc enables).<br>
    Firefox does enable SCTP_ADD_STREAMS so, if data consumers are required, OS can be lower (16 for instance). The mediasoup transport will allocate and announce more outgoing SCTM streams when needed.<br>
    mediasoup-client provides specific per browser/version OS and MIS values via the device.sctpCapabilities getter.<br> */
    export interface TransportNumSctpStreams {
        /**Initially requested number of outgoing SCTP streams (from 1 to 65535). Default 1024.*/
        OS: number;
        /**Maximum number of incoming SCTP streams (from 1 to 65535). Default 1024.*/
        MIS: number;
    }

    type SctpState = 'new' | 'connecting' | 'connected' | 'failed' | 'closed';

    /**A transport connects an endpoint with a mediasoup router and enables transmission of media in both directions by means of Producer and Consumer instances created on it.<br>

    mediasoup implements the following transport classes:<br>
    * WebRtcTransport<br>
    * PlainRtpTransport<br>
    * PipeTransport<br>
    */
    export interface Transport {
        /**Transport identifier.*/
        readonly id: string;
        /**Whether the transport is closed.*/
        readonly closed: boolean;
        /**Custom data Object provided by the application in the transport factory method. The app can modify its content at any time.*/
        readonly data: any;
        /**Transport observer*/
        readonly observer: TransportObserver;

        /**Closes the transport. Triggers a "transportclose" event in all its producers and also "transportclose" event in all its consumers.*/
        close(): void;

        /**Returns current RTC statistics of the transport. Each transport class produces a different set of statistics.*/
        getStats(): Promise<any[]>

        /**Instructs the transport to receive audio or video RTP (or SRTP depending on the transport class). This is the way to inject media into mediasoup.*/
        produce(options: ProducerOptions): Promise<Producer>;

        /**Instructs the transport to send audio or video RTP (or SRTP depending on the transport class). This is the way to extract media from mediasoup.*/
        consume(options: ConsumerOptions): Promise<Consumer>;

        /**Instructs the transport to receive data via SCTP. This is the way to inject data into mediasoup.*/
        produceData(options: DataProducerOptions): Promise<DataProducer>

        /**Instructs the transport to send data via SCTP. This is the way to extract data from mediasoup.*/
        produceData(options: DataConsumerOptions): Promise<DataConsumer>
    }

    export interface TransportObserver {
        /**Emitted when the transport is closed for whatever reason.*/
        on(eventType: "close", handler: () => void): void;
        /**Emitted when a new producer is created.*/
        on(eventType: "newproducer", handler: (producer: Producer) => void): void;
        /**Emitted when a new consumer is created.*/
        on(eventType: "newconsumer", handler: (consumer: Consumer) => void): void;
        /**Emitted when a new data producer is created.*/
        on(eventType: "newdataproducer", handler: (dataProducer: DataProducer) => void): void;
        /**Emitted when a new data consumer is created.*/
        on(eventType: "newdataconsumer", handler: (dataConsumer: DataConsumer) => void): void;
    }

    /**Both initialAvailableOutgoingBitrate and minimumAvailableOutgoingBitrate are just applied when the consumer endpoint supports REMB or Transport-CC.<br>
    If given, minimumAvailableOutgoingBitrate must be higher or equal than initialAvailableOutgoingBitrate.*/
    export interface WebRtcTransportOptions {
        /**Listening IP address or addresses in order of preference /**(first one is the preferred one).*/
        listenIps: TransportListenIp[] | TransportListenIp | string;
        /**Listen in UDP. Default true.*/
        enableUdp?: boolean;
        /**Listen in TCP. Default false.*/
        enableTcp?: boolean;
        /**Listen in UDP. Default false.*/
        preferUdp?: boolean;
        /**Listen in TCP. Default false.*/
        preferTcp?: boolean;
        /**Initial available outgoing bitrate (in bps). Default 600000*/
        initialAvailableOutgoingBitrate?: number
        /**Minimum available outgoing bitrate (in bps) to apply when the consumer endpoint reports less than this value. Use it with caution. Default 300000.*/
        minimumAvailableOutgoingBitrate?: number;
        /**Create a SCTP association. Default false*/
        enableSctp?: boolean;
        /**SCTP streams number.*/
        numSctpStreams?: TransportNumSctpStreams;
        /**Maximum size of data that can be passed to DataProducer's send() method. Default 262144*/
        maxSctpMessageSize?: number;
        /**Custom application data.*/
        appData?: any;
    }

    export interface IceParameters {
        /**ICE username fragment*/
        usernameFragment?: string;
        /**ICE password.*/
        password?: string;
        /**ICE Lite*/
        iceLite: boolean;
    }

    export interface IceCandidate {
        /**Unique identifier that allows ICE to correlate candidates that appear on multiple transports.*/
        foundation: string;
        /**The assigned priority of the candidate.*/
        priority: number;
        /**The IP address of the candidate.*/
        ip: string;
        /**The protocol of the candidate ("udp" / "tcp").*/
        protocol: "udp" | "tcp";
        /**The port for the candidate.*/
        port: number;
        /**The type of candidate (always "host").*/
        type: "host";
        /**The type of TCP candidate (always "passive").*/
        tcpType: "passive";
    }

    export interface DtlsParameters {
        /**DTLS role. Default "auto" */
        role?: DtlsRole;
        /**DTLS fingerprints.*/
        fingerprints: DtlsFingerprints;
    }

    /**Map of DTLS algorithms (as defined in the "Hash function Textual Names" registry initially specified in RFC 4572 Section 8) and their corresponding certificate fingerprint values (in lowercase hex string as expressed utilizing the syntax of "fingerprint" in RFC 4572 Section 5).*/
    export interface DtlsFingerprints {
        /**SHA-1 certificate fingerprint.*/
        "sha-1"?: string;
        /**SHA-224 certificate fingerprint.*/
        "sha-224"?: string;
        /**SHA-256 certificate fingerprint.*/
        "sha-256"?: string;
        /**SHA-384 certificate fingerprint.*/
        "sha-384"?: string;
        /**SHA-512 certificate fingerprint.*/
        "sha-512"?: string;
    }

    /**
     * “new”: No ICE Binding Requests have been received yet.<br>
     * “connected”:	Valid ICE Binding Request have been received, but none with USE-CANDIDATE attribute. Outgoing media is allowed.<br>
     * “completed”: ICE Binding Request with USE_CANDIDATE attribute has been received. Media in both directions is now allowed.<br>
     * “disconnected”: ICE was “connected” or “completed” but it has suddenly failed (this can just happen if the selected tuple has “tcp” protocol).<br>
     * “closed”: ICE state when the transport has been closed.<br>
    */
    export type IceState = "new"
        | "connected"
        | "completed"
        | "disconnected"
        | "closed";

    /** 
     * “auto”: The DTLS role is determined based on the resolved ICE role (the “controlled” role acts as DTLS client, the “controlling” role acts as DTLS server”). Since mediasoup is a ICE Lite implementation it always behaves as ICE “controlled”.
     * “client”: DTLS client role.
     * “server”: DTLS server role.*/
    export type DtlsRole = "auto" | "client" | "server";

    /**
     * “new”: DTLS procedures not yet initiated.<br>
     * “connecting”: DTLS connecting.<br>
     * “connected”: DTLS successfully connected (SRTP keys already extracted).<br>
     * “failed”: DTLS connection failed.<br>
     * “closed”: DTLS state when the transport has been closed.<br>
     */
    export type DtlsState = "new" | "connecting" | "connected" | "failed" | "closed";

    /**A WebRTC transport represents a network path negotiated by both, a WebRTC endpoint and mediasoup, via ICE and DTLS procedures. A WebRTC transport may be used to receive media, to send media or to both receive and send. There is no limitation in mediasoup. However, due to their design, mediasoup-client and libmediasoupclient require separate WebRTC transports for sending and receiving.<br>
    The WebRTC transport implementation of mediasoup is ICE Lite, meaning that it does not initiate ICE connections but expects ICE Binding Requests from endpoints.*/
    export interface WebRtcTransport extends Transport {

        /**Local ICE role. Due to the mediasoup ICE Lite design, this is always “controlled”. */
        readonly iceRole: "controlled";

        /**Local ICE parameters. */
        readonly iceParameters: IceParameters;

        /**Local ICE candidates. */
        readonly iceCandidates: IceCandidate[];

        /**Current ICE state.*/
        readonly iceState: IceState;

        /**The selected transport tuple if ICE is in “connected” or “completed” state. It is undefined if ICE is not established (no working candidate pair was found).*/
        readonly iceSelectedTuple: TransportTuple;

        /**Local DTLS parameters.*/
        readonly dtlsParameters: DtlsParameters;

        /**Current DTLS state.*/
        readonly dtlsState: DtlsState;

        /**The remote certificate in PEM format. It is set once the DTLS state becomes “connected”. The application may want to inspect the remote certificate for authorization purposes by using some certificates utility such as the Node pem module.*/
        readonly dtlsRemoteCert: string;

        /**Local SCTP parameters.*/
        readonly sctpParameters: string;

        /**Current SCTP state.*/
        readonly sctpState: SctpState;

        /**Provides the WebRTC transport with the endpoint parameters. */
        connect(options: { dtlsParameters: DtlsParameters }): Promise<void>;

        /**Set maximum incoming bitrate for media streams sent by the remote endpoint over this WebRTC transport. This method just works when REMB is available in the remote sender.*/
        setMaxIncomingBitrate(bitrate: number): Promise<void>;

        /**Restarts the ICE layer by generating new local ICE parameters that must be signaled to the remote endpoint.*/
        restartIce(): Promise<IceParameters>

        /**Emitted when the transport ICE state changes.*/
        on(eventType: "icestatechange", handler: (iceState: IceState) => void): void;

        /**Emitted after ICE state becomes “completed” and when the ICE selected tuple changes.*/
        on(eventType: "iceselectedtuplechange", handler: (iceSelectedTuple: TransportTuple) => void): void;

        /**Emitted when the transport DTLS state changes.*/
        on(eventType: "dtlsstatechange", handler: (dtlsState: DtlsState) => void): void;

        /**Emitted when the transport SCTP state changes.*/
        on(eventType: "sctpstatechange", handler: (sctpState: SctpState) => void): void;

        //From transport

        /**Emitted when the router this transport belongs to is closed for whatever reason. The transport itself is also closed. A "transportclose" event is triggered in all its producers and a "transportclose" event is triggered in all its consumers.*/
        on(eventType: "routerclose", handler: () => void): void;
    }


    export interface DataProducerOptions {

    }

    export interface DataConsumerOptions {

    }

    export interface PlainRtpTransport extends Transport {

        tuple: any; //TODO

        connect(param: { ip: string; port: number }): Promise<void>;

        consume(options: ConsumerOptions): Promise<Consumer>;

        close(): void;
    }

    export interface ConsumerOptions {
        //TODO
    }

    export interface ProducerOptions {
        //TODO
    }



    export interface Producer {
        id: string;
        observer: ProducerObserver;
        kind: any; //TODO
        type: any; //TODO
        paused: boolean;
        closed: boolean;

        on(eventType: "transportclose", handler: () => void): void;

        on(eventType: "score", handler: (score: number) => void): void; //TODO: Review score type

        on(eventType: "videoorientationchange", handler: (videoOrientation: any) => void): void; //TODO: Review videoOrientation type

        pause(): void;
        resume(): void;

        close(): void;

        getStats(): Promise<any[]> //TODO: Review if more specific type can be used
    }

    export interface Consumer {
        id: string;
        observer: ConsumerObserver;
        producerId: string;
        kind: any; //TODO
        type: any; //TODO
        rtpParameters: any; //TODO
        producerPaused: boolean;
        paused: boolean;
        closed: boolean;

        setPreferredLayers(preferred: LayerId): Promise<void>

        pause(): void;
        resume(): void;

        close(): void;

        getStats(): Promise<any[]> //TODO: Review if more specific type can be used
    }

    export interface LayerId { //TODO: Verify values.
        spatialLayer: 1 | 2 | 3;
        temporalLayer: 1 | 2 | 3;
    }

    export interface DataProducer {
        id: string;
        observer: DataProducerObserver;
    }

    export interface DataConsumer {
        id: string;
        observer: DataConsumerObserver;
    }








    export interface ProducerObserver {
        on(eventType: "close", handler: () => void): void;
    }

    export interface ConsumerObserver {
        on(eventType: "close", handler: () => void): void;
    }

    export interface DataProducerObserver {
        on(eventType: "close", handler: () => void): void;
    }

    export interface DataConsumerObserver {
        on(eventType: "close", handler: () => void): void;
    }

    export interface AudioLevelObserver {
        //TODO
    }

    export interface AudioLevelObserverOptions {
        //TODO
    }

    export interface PlainRtpTransportOptions {
        listenIp: TransportListenIp;
        appData: any;
    }



    export interface RtpCapabilities {
        //TODO
    }



    export interface PipeTransportOptions {
        //TODO
    }

    export interface PipeTransport {
        //TODO
    }
}
